// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var App$ReactTemplate = require("./App.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$ReactTemplate.make("Test Name", /* Female */1, /* :: */[
              /* Jeans */Block.__(1, [/* M */1]),
              /* :: */[
                /* Shirt */Block.__(0, [/* L */2]),
                /* :: */[
                  /* Trousers */Block.__(3, [/* S */0]),
                  /* [] */0
                ]
              ]
            ], /* array */[])), "root");

/*  Not a pure module */
