// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Order$BasicReasonTraining = require("./Order.bs.js");

console.log(Order$BasicReasonTraining.improvedCreateOrder(/* Jeans */Block.__(0, [/* M */1])));

/*  Not a pure module */
